export default [
  "Mining & Metals",
  "Oil & Energy",
  "Pharmaceuticals",
  "Food Production",
  "Aviation & Aerospace",
  "Automotive",
  "Chemicals",
  "Machinery",
  "Textiles",
  "Paper & Forest Products",
  "Printing",
  "Electrical & Electronic Manufacturing",
  "Plastics",
  "Renewables & Environment",
  "Packaging & Containers",
  "Industrial Automation",
  "Computer Hardware",
  "Computer Software",
  "Computer Networking",
  "Internet",
  "Semiconductors",
  "Telecommunications",
  "Motion Pictures & Film",
  "Broadcast Media",
  "Newspapers",
  "Publishing",
  "Information Technology & Services",
  "Writing & Editing",
  "Computer Games",
  "Online Media",
  "Computer & Network Security",
  "Media Production",
  "Banking",
  "Insurance",
  "Financial Services",
  "Investment Banking",
  "Investment Management",
  "Venture Capital & Private Equity",
  "Law Practice",
  "Legal Services",
  "Management Consulting",
  "Biotechnology",
  "Veterinary",
  "Accounting",
  "Architecture & Planning",
  "Research",
  "Executive Office",
  "Marketing & Advertising",
  "Information Services",
  "Environmental Services",
  "Market Research",
  "Public Relations & Communications",
  "Design",
  "Professional Training & Coaching",
  "Translation & Localization",
  "Events Services",
  "Outsourcing/Offshoring",
  "Mechanical Or Industrial Engineering",
  "Photography",
  "Graphic Design",
  "Entertainment",
  "Gambling & Casinos",
  "Sports",
  "Museums & Institutions",
  "Fine Art",
  "Performing Arts",
  "Arts & Crafts",
  "Music",
  "Health, Wellness & Fitness",
  "Animation",
];
